{"f32be134b24015a44cb35606e8b44b5a":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"43ff6696cbce9f1c","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /ClientTest/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000240CE92B620>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))","time":{"start":1742649699712,"stop":1742649699712,"duration":0}}]}}